stages:
  data:
    cmd: python src/data.py
    deps:
      - src/data.py
    outs:
      - data/processed/crf_word2id.json
      - data/processed/crf_tag2id.json
      - data/processed/train_data.json
      - data/processed/dev_data.json
      - data/processed/test_data.json